# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Evan's Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: evantoli
github_username:  evantoli
linkedin_username:  evantoli
excerpt_separator: <!--end-of-excerpt-->


# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title/


exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"

# my own theme variables
author: Evan Toli
banner: /images/banner-bush-floor-20151111-112701-1795.jpg
banner_slim: /images/banner-bush-floor-slim-20151111-112701-1795.jpg
